### ISSUE TITLE
Point Movement 

### ISSUE THREAD

**Issue by jesscs** [CSE512-15S/a3-jhoffs-fiannaca-jesscs#6]
Points only move on release

**Comment by fiannaca** [comment]
I assume this is about the slider? If so, then the problem is that we are listening to on-core-change instead of observing changes to the value property of the slider. Data bind the value property of the slider to a variable on app and then observe changes on that variable to capture the value of the slider in realtime. 

On the slider tag:

value="{{someVariable}}" 

In app.js:

app.someVariable = initialValue;

Object.observe(app.someVariable, 
    function(changes) {
        changes.forEach(function(change){
            //Do something with current value
        });
    });

**Comment by jesscs** [comment]
For some reason the object.observe function isn't working; it says "Object.observe cannot observe non-object."  I'm trying to figure it out, but if you know what it is from the top of your head let me know :)

**Comment by jesscs** [comment]
So I changed it to 
Object.observe(app.,      function(changes) {        
 changes.forEach(function(change){             
call function on app.someVariable         });     });

But it still only updates when I release

**Comment by jesscs** [comment]
The "pin" thing (the circle that's supposed to show the episode number) isn't working either, and that's supposed to automatically happen when the slider is moved

**Comment by jesscs** [comment]
Fixed it!  I use the "immediate value" instead of the value, that seems to work
